<a href="https://colab.research.google.com/github/jeonghar1m/ITECT-Assignment/blob/main/11%EC%9D%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#2022. 1. 11

# Q1. 학생 정보 검색
- 3명의 학생 정보를 갖고 있는 dictionary형 변수를 생성하여 관리하는 프로그램을 작성하자. 학번이 Key가 되고, Value로는 이름, 생년월일, 전화번호가 주어진다. Value에 해당하는 내용은 list 자료형을 사용하여 선언한다.
- 조건 <학생정보>

학번: 20201112

이름: 홍익대

생년월일: 2000년 5월 8일

전화번호: 02-4543-4444

--------------------------------------------

학번: 20195555

이름: 고려대

생년월일: 1999년 10월 24일

전화번호: 010-7864-9900

--------------------------------------------

학번: 20201878

이름: 서울대

생년월일: 2000년 1월 7일

전화번호: 010-8856-9092

--------------------------------------------

위 학생 정보로 dictionary를 생성하고, dictionary에서 
Key에 해당하는 학번 20201112를 입력하면 이름이 연세대인 사람의 이름, 생년월일, 전화번호를 출력한다.

<출력예시>  
학번을 입력하세요: 20201112  
<찾았습니다>  
이름: 홍익대  
생년월일: 2000년 5월 8일  
전화번호: 02-4543-4444 

학번을 입력하세요: 20221111  
없는 정보입니다.

학번을 입력하세요: 종료  
종료합니다.

In [9]:
# 데이터 정의
student = {"20201112" : ["홍익대", "2000년 5월 8일", "02-4543-4444"],
           "20195555" : ["고려대", "1999년 10월 24일", "010-7864-9900"],
           "20201878" : ["서울대", " 2000년 1월 7일", "010-8856-9092"]}

In [11]:
while True:
  print("현재 데이터")
  print(student)
  menu = int(input("메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)"))
  # 데이터 검색
  if (menu == 1):
    stNumber = input("학번을 입력하세요: ")
    stKeys = student.keys()
    label = ["이름", "생년월일", "전화번호"]
    i = 0
    if stNumber in stKeys:
      stInfo = student.get(stNumber)
      for info in stInfo:
        print(label[i], ": ",info)
        i = i + 1
    else:
      print("학번 %s는 없습니다." %stNumber)
    print("----------------------------------------------------------------------------")
  #데이터 입력
  elif (menu == 2):
    print("데이터 입력")
    newStNumber = input("학번을 입력하세요: ")
    newStName = input("이름을 입력하세요: ")
    newStBirthday = input("생년월일을 입력하세요(2000년 1월 1일 형식): ")
    newStPhone = input("전화번호를 입력하세요(010-1111-1111 형식): ")
    # student.update({newStNumber: [newStName, newStBirthday, newStPhone]})
    student[newStNumber] = [newStName, newStBirthday, newStPhone]
    print("----------------------------------------------------------------------------")
  elif(menu == 3):
    print("데이터 수정")
    stNumber = input("학번을 입력하세요: ")
    stKeys = student.keys()
    i = 0
    if stNumber in stKeys:
      newStName = input("이름을 입력하세요: ")
      newStBirthday = input("생년월일을 입력하세요(2000년 1월 1일 형식): ")
      newStPhone = input("전화번호를 입력하세요(010-1111-1111 형식): ")
      student[stNumber] = [newStName, newStBirthday, newStPhone]
    else:
      print("학번 %s는 없습니다." %stNumber)
    print("----------------------------------------------------------------------------")
  elif menu == 4:
    print("데이터 삭제")
    stNumber = input("학번을 입력하세요: ")
    stKeys = student.keys()
    i = 0
    if stNumber in stKeys:
      del student[stNumber]
    else:
      print("학번 %s는 없습니다." %stNumber)
    print("----------------------------------------------------------------------------")
  elif menu == 5:
    print("종료합니다.")
    break
  else:
    print("메뉴를 잘못 선택하셨어요.")
    print("----------------------------------------------------------------------------")

현재 데이터
{'20201112': ['홍익대', '2000년 5월 8일', '02-4543-4444'], '20195555': ['고려대', '1999년 10월 24일', '010-7864-9900'], '20201878': ['서울대', ' 2000년 1월 7일', '010-8856-9092']}
메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)1
학번을 입력하세요: 20201112
이름 :  홍익대
생년월일 :  2000년 5월 8일
전화번호 :  02-4543-4444
----------------------------------------------------------------------------
현재 데이터
{'20201112': ['홍익대', '2000년 5월 8일', '02-4543-4444'], '20195555': ['고려대', '1999년 10월 24일', '010-7864-9900'], '20201878': ['서울대', ' 2000년 1월 7일', '010-8856-9092']}
메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)1
학번을 입력하세요: 20201111
학번 20201111는 없습니다.
----------------------------------------------------------------------------
현재 데이터
{'20201112': ['홍익대', '2000년 5월 8일', '02-4543-4444'], '20195555': ['고려대', '1999년 10월 24일', '010-7864-9900'], '20201878': ['서울대', ' 2000년 1월 7일', '010-8856-9092']}
메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)2
데이터 입력
학번을 입력하세요: 20151234
이름을 입력하세요: 정하림
생년월일을 입력하세요(2000년 1월 1일 형식): 1997년 7월 14일
전화번호를 입력하세요(010-1111-1111 형식): 010-1111-1111
----------------------------------------------------------------------------
현재 데이터
{'20201112': ['홍익대', '2000년 5월 8일', '02-4543-4444'], '20195555': ['고려대', '1999년 10월 24일', '010-7864-9900'], '20201878': ['서울대', ' 2000년 1월 7일', '010-8856-9092'], '20151234': ['정하림', '1997년 7월 14일', '010-1111-1111']}
메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)3
데이터 수정
학번을 입력하세요: 20201111
학번 20201111는 없습니다.
----------------------------------------------------------------------------
현재 데이터
{'20201112': ['홍익대', '2000년 5월 8일', '02-4543-4444'], '20195555': ['고려대', '1999년 10월 24일', '010-7864-9900'], '20201878': ['서울대', ' 2000년 1월 7일', '010-8856-9092'], '20151234': ['정하림', '1997년 7월 14일', '010-1111-1111']}
메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)3
데이터 수정
학번을 입력하세요: 20201112
이름을 입력하세요: 홍삼대
생년월일을 입력하세요(2000년 1월 1일 형식): 2001년 4월 3일
전화번호를 입력하세요(010-1111-1111 형식): 031-1234-5657
----------------------------------------------------------------------------
현재 데이터
{'20201112': ['홍삼대', '2001년 4월 3일', '031-1234-5657'], '20195555': ['고려대', '1999년 10월 24일', '010-7864-9900'], '20201878': ['서울대', ' 2000년 1월 7일', '010-8856-9092'], '20151234': ['정하림', '1997년 7월 14일', '010-1111-1111']}
메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)4
데이터 삭제
학번을 입력하세요: 20202222
학번 20202222는 없습니다.
----------------------------------------------------------------------------
현재 데이터
{'20201112': ['홍삼대', '2001년 4월 3일', '031-1234-5657'], '20195555': ['고려대', '1999년 10월 24일', '010-7864-9900'], '20201878': ['서울대', ' 2000년 1월 7일', '010-8856-9092'], '20151234': ['정하림', '1997년 7월 14일', '010-1111-1111']}
메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)4
데이터 삭제
학번을 입력하세요: 20151234
----------------------------------------------------------------------------
현재 데이터
{'20201112': ['홍삼대', '2001년 4월 3일', '031-1234-5657'], '20195555': ['고려대', '1999년 10월 24일', '010-7864-9900'], '20201878': ['서울대', ' 2000년 1월 7일', '010-8856-9092']}
메뉴를 선택하세요: (1:검색, 2:입력, 3:수정, 4: 삭제, 5: 종료)5
종료합니다.

In [ ]:
#형식지정자 %
score1 = 98.563
print(score1)
print("형식지정자 사용 %3.2f"%score1)

98.563
형식지정자 사용 98.56

In [ ]:
print("형식지정자 사용 %3d"%score1)

형식지정자 사용  98

In [ ]:
name1 = "문소영"
print("name = ", name1)
print("name3 = %s" %name1, name1)
print("name = %s, score=%3.1f"%(name1, score1))

name =  문소영
name3 = 문소영 문소영
name = 문소영, score=98.6